In [1]:
import numpy as np
b = np.array([1,2,3,4])
c = np.array([[1,2],
              [3,4]])
print(np.prod(b)) # 1*2*3*4
print(np.prod(c, axis=0)) # [1*3, 2*4] 0은 열
print(np.prod(c, axis=1)) # [1*2,2*4] 1은 행
print(np.sum(b))  # 1+2+3+4
print(np.sum(b, keepdims=True)) # [1+2+3+4]
print(np.sum(c, axis=0)) # [1+3, 2+4]
print(np.sum(c, axis=1)) # [1+2, 3 +4]

24
[3 8]
[ 2 12]
10
[10]
[4 6]
[3 7]


In [22]:
import numpy as np
a = np.array([2,4,6,8]).reshape(2,2)
b = np.array([2,2,2,2]).reshape(2,2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.matmul(a,b))

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]
[[ 4  6]
 [ 8 10]]
[[0 2]
 [4 6]]
[[ 4  8]
 [12 16]]
[[1. 2.]
 [3. 4.]]
[[12 12]
 [28 28]]


In [23]:
import numpy as np
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(np.matmul(a1,a2))
print(a1**3)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [27]:
import numpy as np
import datetime
li = range(1,1000000)
s = datetime.datetime.now()
li2 = []
for i in li:
    li2.append(i*2)
print(datetime.datetime.now()-s)
ar = np.array(li)
s = datetime.datetime.now()
arr2 = ar * 2
s = datetime.datetime.now()
print(datetime.datetime.now()-s)

0:00:00.198905
0:00:00.000088


In [29]:
import numpy as np
# scipy : science python 과학 연산을 위한 모듈을 가진 라이브러리
# scipy.stats : 통계에 대한 모듈
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
               4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
# x.sort() # 원본 데이터를 작은 것부터 큰수까지 오름차순으로 변경
print(x)
print(np.percentile(x, 0))  # 최소값
print(np.percentile(x, 25)) # 25%위치값 1사분위수 1/4
print(np.percentile(x, 50)) # 중앙값    2사분위수 1/4 * 2
print(np.percentile(x, 75)) # 75%위치값 3사분위수 1/4 * 3
print(np.percentile(x, 100)) # 최대값

[ 18   5  10  23  19  -8  10   0   0   5   2  15   8   2   5   4  15  -1
   4  -7 -24   7   9  -6  23 -13]
-24.0
0.0
5.0
10.0
23.0


In [4]:
import numpy as np
ar1 = np.array([0,1,2,3,4,5,6,7,8,9])
ar2 = np.arange(10)
print(ar1)
print(ar2)
ar3 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
ar4 = ar2.reshape(2,5)  # 행이 2, 열이 5
ar5 = ar2.reshape(2,-1) # 2행으로 열의 알아서 맞춰
print(ar3)
print(ar4)
print(ar5)
ar6 = np.linspace(0,1,6) # 시작, 끝, 갯수
print(ar6)
ar7 = np.linspace(0,1,5,endpoint=False)
print(ar7)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [5]:
import numpy as np
d = np.array([[
    [1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[11,12,13,14],[15,16,17,18],[19,20,21,22]] ])
print(d)
print(d.shape)
# 대괄호 2개 2, 대괄호 1개 3, 인자가 4

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
(2, 3, 4)


In [6]:
import numpy as np
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
#     데이터  구조     데이터타입  행의 갯수   열의 갯수
print(arr, arr.shape, arr.dtype, len(arr), len(arr[0]))

[[10 20 30 40]
 [50 60 70 80]] (2, 4) int64 2 4


In [7]:
import numpy as np
ar = np.arange(5).reshape(1,5)
br = np.arange(5).reshape(5,1)
print(ar)
print(br)
print(ar+br) # broadcast 행열을 맞춰서 연산

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [9]:
import numpy as np
ar1 = np.array([1,2,3])  # 부족한 쪽에서 확장한 것으로 가정하여 실행
print(ar1*2)
ar2 = np.array([[2,3,4],[6,7,9]]) # 열의 갯수가 맞아야 된다
print(ar1+ar2)
# br1 = np.array([2,3])
# br2 = np.array([[2,3,4],[6,7,8]])
# print(br1+br2)

[2 4 6]
[[ 3  5  7]
 [ 7  9 12]]


In [11]:
import numpy as np
a1 = np.ones((2,3))
print(a1)
a2 = np.zeros((2, 2))
print(a2)
# hstack/vstack : 두개를 붙인 새로운 배열을 생성
# hstack : horizontal stack 수평으로 붙임 
print(np.hstack([a1, a2]))
a3 = np.zeros((3,3))
# vstack vertical stack  수직으로 이어 붙임 
print(a3)
a4 = np.vstack([a1, a3])
print(a4)
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np
ar1 = np.array([1,2,3,4])
br1 = np.array([5,6,7,8])
cr1 = np.concatenate((ar1, br1)) 
print(cr1)
ar2 = np.array([[1, 2],
                [3,4]])
br2 = np.array([[5, 6],
                [7,8]])
cr1 = np.concatenate((ar2,br2), axis=0) 
cr2 = np.concatenate((ar2,br2), axis=1)
print(cr1)
print(cr2)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [13]:
import numpy as np
ar1 = np.array([1,2,3])
print(ar1, ar1.dtype)
ar2 = np.array((['1', 2, 3.0]))
print(ar2, ar2.dtype)
ar3 = np.array(([1, 2, 3.0]))
print(ar3, ar3.dtype)
ar4 = ar1.astype(np.float)
print(ar4, ar4.dtype)
ar5 = ar1.astype(np.string_)
print(ar5, ar5.dtype)
ar6 = ar1.astype(np.unicode_)
print(ar6, ar6.dtype)

[1 2 3] int64
['1' '2' '3.0'] <U3
[1. 2. 3.] float64
[1. 2. 3.] float64
[b'1' b'2' b'3'] |S21
['1' '2' '3'] <U21


In [14]:
# flatten, ravel은 다차원 배열을 1차원으로 변경
import numpy as np
arr = np.array([[[0,1],[2,3],[4,5]],
                [[6,7],[8,9],[10,11]]])
print(arr, arr.shape)
print(arr.flatten())
print(arr.ravel())

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] (2, 3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# 단항함수
import numpy as np
ar = np.array([10, 1, 2, 3, 4])
br = np.array([1.23, 4.567, 2.76])
cr = np.array([-7, 0, 2])
print(np.sqrt(ar))
print(np.square(ar))
print(np.modf(br))  # 소수부분과 정수를 분리
print(np.sign(cr))  # 음수(-1), 0, 양수(1)

[3.16227766 1.         1.41421356 1.73205081 2.        ]
[100   1   4   9  16]
(array([0.23 , 0.567, 0.76 ]), array([1., 4., 2.]))
[-1  0  1]


In [16]:
import numpy as np
#               0 1 2
#              -3-2-1
ar1 = np.array([1,2,3])
print(ar1[0], ar1[1], ar1[2])
print(ar1[-1], ar1[-2], ar1[-3])
ar2 = np.array([[1,2],[3,4]])
#         행 열
print(ar2[0][0],ar2[0][1],ar2[1][0],ar2[1][1])
#         행열
print(ar2[0,0],ar2[0,1],ar2[1,0],ar2[1,1])
print(ar2[-1][-1],ar2[-2][-2])
print(ar2[-1,-1],ar2[-2,-2])
#         0행    1행
print(ar2[0], ar2[1])

1 2 3
3 2 1
1 2 3 4
1 2 3 4
4 1
4 1
[1 2] [3 4]


In [17]:
import numpy as np
# 21 29 ar, 3행 3열 shape, dtype, type
ar = np.arange(21,30).reshape(3,3)
print(ar)
print(ar.shape,ar.dtype,type(ar))
# 25,  21, 29
print(ar[0,0],ar[1,1],ar[2,2])
print(ar[0][0],ar[1][1],ar[2][2])
# 0행, 마지막 출력
print(ar[0])
print(ar[-1][-1])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
(3, 3) int64 <class 'numpy.ndarray'>
21 25 29
21 25 29
[21 22 23]
29


In [18]:
import numpy as np
ar = np.empty((10,5)) # 가비지 값
# print(ar)
for i in range(10):
    ar[i] = i     # 행 전체에 같은 값저장
print(ar)
#         행(1,3,5,7)
ar2 = ar[[1,3,5,7]] # 인덱스 배열, fancy 결과가 배열
print(ar2)
#         행    열
ar3 = ar[[0,1],[3,4]] # 0행3열, 1행 4열
print(ar3)
#       행   앞에서 선택한 데이터 중에서 행은 전부 열은 3과 4열
#               행  열
ar4 = ar[[0,1]][:,[3,4]]
print(ar4)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9.]]
[[1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [5. 5. 5. 5. 5.]
 [7. 7. 7. 7. 7.]]
[0. 1.]
[[0. 0.]
 [1. 1.]]


In [19]:
import numpy as np
# ar : 1 ~ 20  4행 5열
ar1 = np.arange(1, 21).reshape(4, 5); print(ar1)
# 1행, 3행
ar2 = ar1[[1,3]]; print(ar2)
# 0행 3열,  1행 4열
ar3 = ar1[[0,1],[3,4]];  print(ar3)
# 0과 1행 중에서 3열과 4열
ar4 = ar1[[0,1]][:,[3,4]]; print(ar4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[ 4 10]
[[ 4  5]
 [ 9 10]]


In [20]:
import numpy as np
data1 = [1,2,3,4,5]
print(data1, type(data1))
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1))
arr2 = np.array(data1)
print(arr2, type(arr2))
print(arr1.shape, arr1.dtype)
arr3 = np.array([[1,2,3],[2,3,4]])
print(arr3, arr3.shape)
data2 = [2, 4, 5, 1.2]
print(data2)
arr4 = np.array(data2) # array는 데이터형이 같아야 범위가 넓은 쪽으로 변경
print(arr4, arr4.dtype)

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>
(5,) int64
[[1 2 3]
 [2 3 4]] (2, 3)
[2, 4, 5, 1.2]
[2.  4.  5.  1.2] float64


In [21]:
import numpy as np
list1 = [4, 5, 6, 7.0]
print(list1, type(list1))
arr1 = np.array(list1)
print(arr1, type(arr1), arr1.shape, arr1.dtype)

[4, 5, 6, 7.0] <class 'list'>
[4. 5. 6. 7.] <class 'numpy.ndarray'> (4,) float64


In [31]:
import numpy as np
# 5 ~ 10사이 정수 10개 균등하게 10개
r1 = np.random.randint(5, 10, size=10)
print(r1)
# 0 과 10 2행 5열 균등하게 정수
r2 = np.random.randint(0,10, size=(2,5))
print(r2)
data2 = np.random.randint(-100, 100, 10000)

[5 8 9 5 9 6 6 6 7 5]
[[9 4 4 0 3]
 [2 7 5 2 0]]


In [32]:
import numpy as np
# 평균이 0이고 표준편차가 1인 정규분포 5개
print(np.random.normal(size=5))
print(np.random.normal(size=(2,3)))

[-2.6573258  -0.23511348  0.35794008 -1.63995747  2.01780971]
[[-0.78370512  0.24952209  1.06762656]
 [ 0.53598406 -3.66950918  0.59201979]]


In [36]:
import numpy as np
arr = np.random.normal(10, 10, size=10000)
print(arr)


[ 5.38411881 23.49803181 -0.37470484 ... 26.1606493   3.20298605
 13.99232336]


In [37]:
import numpy as np
# 실행할 때마다 같은 램덤값 사용
np.random.seed(seed=123)
print(np.random.normal(size=5))
print(np.random.normal(size=(2,3)))
print(np.random.normal(size=5))

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
[[ 1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615]]
[-0.09470897  1.49138963 -0.638902   -0.44398196 -0.43435128]


In [38]:
import numpy as np
ar1 = np.arange(20).reshape(5,4)
print(ar1)
br1 = np.array(['A','B','C','A','C'])
print((br1=='A') | (br1=='C'))  # or, and를 사용할 때는 ()이용
print(ar1[(br1=='A') | (br1=='C')]) # True행만 출력
print(ar1[br1=='A',2]) # True행 중에서 2열
#         행       열
print(ar1[br1=='A',:2]) # True행 중에서 2열까지
ar1[br1=='A'] = 100  # True행에만 값을 100으로 변경
print(ar1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ True False  True  True  True]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 2 14]
[[ 0  1]
 [12 13]]
[[100 100 100 100]
 [  4   5   6   7]
 [  8   9  10  11]
 [100 100 100 100]
 [ 16  17  18  19]]


In [39]:
import numpy as np
# ar 21 40  5핼 4열
ar = np.arange(21,41).reshape(5,4)
br = np.array(['A','B','C','A','C'])
# br이 A가 아닌 경우만 출력
print(ar[br!='A'])
# 위 조건에서 3열 출력
print(ar[br!='A',3])
# 위 조건에서 2열부터 끝까지 출력
print(ar[br!='A',2:])
# 위조건 데이터만 67로 변경하고 출력
ar[br!='A'] = 67; print(ar)

[[25 26 27 28]
 [29 30 31 32]
 [37 38 39 40]]
[28 32 40]
[[27 28]
 [31 32]
 [39 40]]
[[21 22 23 24]
 [67 67 67 67]
 [67 67 67 67]
 [33 34 35 36]
 [67 67 67 67]]


In [40]:
import numpy as np
ar = np.arange(1,21).reshape(5,4)
print(ar)
print(ar[[1,2]]) # index가 1~2
print(ar[1:3])   # 행이 1부터 3행
print(ar[[-2, -1]]) # 인덱스가 -2 또는 -1
print(ar[-2:])   # -2행부터 끝까지
print(ar[[0,2,4]][:,[0,2]]) # 0,2,4행중에서 행은 전부 열은 0또는 2열
# np.ix_인덱스가 행      열
print(ar[np.ix_([0,2,4],[0,2])])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]]
[[13 14 15 16]
 [17 18 19 20]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[[ 1  3]
 [ 9 11]
 [17 19]]


In [41]:
import numpy as np
x = np.array([[2, 1, 6], [0, 7, 4],  [5, 3, 2]])
print(x)
print(np.sort(x, axis=1))  # 좌우 오름차순
print(np.sort(x, axis=0))  # 상하 오름차순
print(np.sort(x, axis=0)[::-1]) # 상하 내림차순

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


In [42]:
import numpy as np
ar = np.array([[3, 8, 2],[9,1,4],[6,7,3]])
print(ar)
print(np.sort(ar, axis=0)) # 상하로 작은 순서
print(np.sort(ar, axis=0)[::-1]) # 상하로 큰순서
print(np.sort(ar, axis=1)) # 좌우로 작은 순서
print(np.sort(ar, axis=1)[:,::-1])  # 좌우로 큰순서

[[3 8 2]
 [9 1 4]
 [6 7 3]]
[[3 1 2]
 [6 7 3]
 [9 8 4]]
[[9 8 4]
 [6 7 3]
 [3 1 2]]
[[2 3 8]
 [1 4 9]
 [3 6 7]]
[[8 3 2]
 [9 4 1]
 [7 6 3]]


In [43]:
import numpy as np
b1 = np.ones(10) # 크기가 10인 1로 채워진 1차원 행열
print(b1)
b2 =np.zeros((3,3)) # 3행3열 0으로채워진 행열
print(b2)
ar1 = np.eye(2) # 항등(단위)행열, 대닥선은 1 나머지는 0 실수
print(ar1)
ar2 = np.eye(2, dtype=int) # 항등(단위)행열, 대닥선은 1 나머지는 0 정수
print(ar2)
ar3 = np.eye(3, k=1)  # 대각선 위치를 위로 한칸 이동
print(ar3)
ar4 = np.eye(3, k=-1) # 대각선 위치를 아래로 한칸 이동
print(ar4)
ar = np.arange(9).reshape((3,3))
print(ar)
d1 = np.diag(ar)  # 대각선 데이터 읽기
print(d1)
d2 = np.diag(ar, k=1) # 한칸위 대각선
print(d2)
d3 = np.diag(ar, k=-1) # 한칸 아래 대각선
print(d3)
d4 = np.empty((3,3))  # 가비지(현재 위치에 있는 값, 의미없음) 값
print(d4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1 0]
 [0 1]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]
[[1.5e-323 4.0e-323 9.9e-324]
 [4.4e-323 4.9e-324 2.0e-323]
 [3.0e-323 3.5e-323 1.5e-323]]


In [44]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5,
              4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print('갯수 :',len(x))
print('합계 :',np.sum(x))
print('평균 :',np.mean(x), np.average(x))
print('분산 :',np.var(x))
print('표준편차 :',np.std(x))
print('최대 :',np.max(x))
print('최소 :',np.min(x))
print('중앙값 :',np.median(x))

갯수 : 26
합계 : 125
평균 : 4.8076923076923075 4.8076923076923075
분산 : 115.23224852071006
표준편차 : 10.734628476137871
최대 : 23
최소 : -24
중앙값 : 5.0


In [45]:
import numpy as np
ar = np.arange(10).reshape(2,5)
print(ar)
print(ar.T) # 행과 열을 변경
print(ar.transpose()) # 행과 열을 변경
# br 0 19 4행 5열 -> 행과 열을 교환
br = np.arange(20).reshape(4, 5)
print(br)
print(br.T)
print(br.transpose())


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [47]:
#                    0 1 2    2 1 0     1, 0, 2
import numpy as np # 2 3 2 -> 2 3 2 ->  3  2  2
ar = np.array([
    [[1,2],  [3,4],  [5,6]],
    [[71,72], [73,74],  [75,76]]])
print(ar)
print('\n\n')
print(ar.transpose())
print('\n\n')
print(ar.transpose(2, 1 ,0))
print('\n\n')
print(ar.transpose(1 ,0, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[71 72]
  [73 74]
  [75 76]]]



[[[ 1 71]
  [ 3 73]
  [ 5 75]]

 [[ 2 72]
  [ 4 74]
  [ 6 76]]]



[[[ 1 71]
  [ 3 73]
  [ 5 75]]

 [[ 2 72]
  [ 4 74]
  [ 6 76]]]



[[[ 1  2]
  [71 72]]

 [[ 3  4]
  [73 74]]

 [[ 5  6]
  [75 76]]]


In [51]:
from pandas import Series, DataFrame
items = {'code': [1,2,3,4,5,6],
'name':['apple','watermelon','oriental melon','banana','lemon','mango'],
'manufacture': ['korea', 'korea', 'korea','philippines','korea',
                'taiwan'],
'price':[1500, 15000,1000,500,1500,700]}
data = DataFrame(items)
print(data)


   code            name  manufacture  price
0     1           apple        korea   1500
1     2      watermelon        korea  15000
2     3  oriental melon        korea   1000
3     4          banana  philippines    500
4     5           lemon        korea   1500
5     6           mango       taiwan    700


In [52]:
from pandas import DataFrame, Series
import numpy as np
data = {"2015": [990432,3448737,2890451,2466052],
        "2010": [9631482, 3393191, 2632035, 2431774],
        "2005": [9762546, 3512547, 2517680, 2456016],
        "2000": [9853972, 3655437, 2466338, 2473990],
        "지역": ["수도권","경상권","수도권","경상권"],
        "2010-2015증가율":[0.0283,0.0163,0.0982,0.0141]
        }
index = ["서울","부산","인천","대구"]
df = DataFrame(data, index=index,columns=column)
print(df)
print(df.index)


     지역     2015     2010     2005     2000  2010-2015증가율
서울  수도권   990432  9631482  9762546  9853972        0.0283
부산  경상권  3448737  3393191  3512547  3655437        0.0163
인천  수도권  2890451  2632035  2517680  2466338        0.0982
대구  경상권  2466052  2431774  2456016  2473990        0.0141
Index(['서울', '부산', '인천', '대구'], dtype='object')


In [53]:
from pandas import Series, DataFrame
items = {'1':{'name':'apple', 'manufacture':'korea', 'price':1500},
'2': {'name': 'watermelon', 'manufacture': 'korea', 'price': 15000},
'3': {'name':'oriental melon','manufacture': 'korea','price': 1000},
'4': {'name': 'banana', 'manufacture': 'philippines', 'price': 500},
'5': {'name': 'lemon', 'manufacture': 'korea', 'price': 1500},
'6': {'name': 'mango', 'manufacture': 'korea', 'price': 700}}
data = DataFrame(items)
print(data)
print(data['1'])
print(data[['1','3']])
print(data[:1])
print(data[1:3])
data = data.T   #  행과 열을 변경
# 컬럼명이 price중에서 값이 10001ㅗ다 큰 데이터
print(data['price']>1000)
# True데이터 만 출력력print(data[data['price']>1000])
print(data.iloc[0])
print(data.loc[:'1','name'])
print(data.loc['1':'2',['name','price']])
print(data.loc[:'3',['name','price']])   # 문자일 때는 포함
print(data.loc[data.price>1000,['name','price']])

                 1           2               3            4      5      6
name         apple  watermelon  oriental melon       banana  lemon  mango
manufacture  korea       korea           korea  philippines  korea  korea
price         1500       15000            1000          500   1500    700
name           apple
manufacture    korea
price           1500
Name: 1, dtype: object
                 1               3
name         apple  oriental melon
manufacture  korea           korea
price         1500            1000
          1           2               3       4      5      6
name  apple  watermelon  oriental melon  banana  lemon  mango
                 1      2      3            4      5      6
manufacture  korea  korea  korea  philippines  korea  korea
price         1500  15000   1000          500   1500    700
1     True
2     True
3    False
4    False
5     True
6    False
Name: price, dtype: bool
name           apple
manufacture    korea
price           1500
Name: 1, dtype: obje

In [54]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4), columns=["A","B","C","D"])
print(df)
print(df.iloc[0])
#             행, 열
print(df.iloc[0,1])
print(df.iloc[:2,2]) # 0/1행 2열
print(df.iloc[0,-2:]) # 0행 -2열부터 끝꺼지
print(df.iloc[1:3, 1:3]) # 1/2행, 1/2열
print(df.iloc[-1])  # 마지막 행
df.iloc[-1] = df.iloc[-1] *2
print(df)

    A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
A    10
B    11
C    12
D    13
Name: 0, dtype: int64
11
0    12
1    16
Name: C, dtype: int64
C    12
D    13
Name: 0, dtype: int64
    B   C
1  15  16
2  19  20
A    18
B    19
C    20
D    21
Name: 2, dtype: int64
    A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  36  38  40  42


In [57]:
import pandas as pd
import numpy as np
fr = pd.DataFrame(np.arange(8).reshape(2,4), columns=['d','a','b','c'])
print(fr)
print('\n')
print(fr.sort_values(by="b"))  # b값이 오름차순
print('\n')
print(fr.sort_values(ascending=False,by="b"))  # b값이 내림차순

   d  a  b  c
0  0  1  2  3
1  4  5  6  7


   d  a  b  c
0  0  1  2  3
1  4  5  6  7


   d  a  b  c
1  4  5  6  7
0  0  1  2  3


In [60]:
import pandas as pd
items = {'apple':{'count':None,'price':None},
         'banana': {'count':None, 'price': 15000},
         'melon': { 'count':7,'price': 1000},
         'kiwi': {'count':20,'price': 500},
         'mango': {'count':30,'price': 1500},
         'orange': { 'count':4,'price': 700}}
data = pd.DataFrame(items).T
print(data)
print(data.fillna(0))         # NA 0으로
print(data.dropna())          # NA를 drop

       count  price
apple   None   None
banana   NaN  15000
melon      7   1000
kiwi      20    500
mango     30   1500
orange     4    700
        count    price
apple       0      0.0
banana      0  15000.0
melon       7   1000.0
kiwi       20    500.0
mango      30   1500.0
orange      4    700.0
       count price
melon      7  1000
kiwi      20   500
mango     30  1500
orange     4   700


In [61]:
import pandas as pd
# def f1(x):
#     return x.sum()
f1 = lambda x:x.sum()
items = {'apple':{'count':10,'price':1500},
         'banana': {'count':5, 'price': 15000},
         'melon': { 'count':7,'price': 1000},
         'kiwi': {'count':20,'price': 500},
         'mango': {'count':30,'price': 1500},
         'orange': { 'count':4,'price': 700}}
data1 = pd.DataFrame(items).T # T는 transpose() 행열 변경
print(data1)
print(data1.apply(f1))  # 열별 합계
print(data1.apply(f1, axis=1))  # 행별로 합계

        count  price
apple      10   1500
banana      5  15000
melon       7   1000
kiwi       20    500
mango      30   1500
orange      4    700
count       76
price    20200
dtype: int64
apple      1510
banana    15005
melon      1007
kiwi        520
mango      1530
orange      704
dtype: int64


In [65]:
import pandas as pd
items = {'apple':{'count':10,'price':1500},
         'banana': {'count':5, 'price': 15000},
         'melon': { 'count':7,'price': 1000},
         'kiwi': {'count':20,'price': 500},
         'mango': {'count':30,'price': 1500},
         'orange': { 'count':4,'price': 700}}
data1 = pd.DataFrame(items).transpose() # 행열 변경
print(data1)
print(data1.applymap(lambda x:x*2))  # 건건이 적용

        count  price
apple      10   1500
banana      5  15000
melon       7   1000
kiwi       20    500
mango      30   1500
orange      4    700
        count  price
apple      20   3000
banana     10  30000
melon      14   2000
kiwi       40   1000
mango      60   3000
orange      8   1400


In [67]:
import pandas as pd
# dictionary
data = {"2015": [990432,3448737,2890451,2466052],
        "2010": [9631482, 3393191, 2632035, 2431774],
        "2005": [9762546, 3512547, 2517680, 2456016],
        "2000": [9853972, 3655437, 2466338, 2473990],
        "지역": ["수도권","경상권","수도권","경상권"],
        "2010-2015증가율":[0.0283,0.0163,0.0982,0.0141]
        }
column=["지역","2015","2010","2005","2000","2010-2015증가율"]
df = pd.DataFrame(data,columns=column)
print(df['지역'])
print(df[['2010','2015']])
print(df['2010'])    # 컬럼명 x
print(df[['2010']])  # 컬럼명 포함
print(type(df['2010']))    # 컬럼명 x, df -> Series
print(type(df[['2010']]))  # 컬럼명 포함  -> dataframe유지

0    수도권
1    경상권
2    수도권
3    경상권
Name: 지역, dtype: object
      2010     2015
0  9631482   990432
1  3393191  3448737
2  2632035  2890451
3  2431774  2466052
0    9631482
1    3393191
2    2632035
3    2431774
Name: 2010, dtype: int64
      2010
0  9631482
1  3393191
2  2632035
3  2431774
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [69]:
df.to_csv('test.csv')

In [70]:
pd.read_csv('test.csv')

Unnamed: 0   지역     2015     2010     2005     2000  2010-2015증가율
0           0  수도권   990432  9631482  9762546  9853972        0.0283
1           1  경상권  3448737  3393191  3512547  3655437        0.0163
2           2  수도권  2890451  2632035  2517680  2466338        0.0982
3           3  경상권  2466052  2431774  2456016  2473990        0.0141